# Generated by Django 3.2 on 2024-03-15 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtor', '0002_alter_produtor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtor',
            options={'ordering': ['nome'], 'verbose_name': 'Produtor', 'verbose_name_plural': 'Produtores'},
        ),
        migrations.AlterModelTable(
            name='produtor',
            table='brain_ag_produtor',
        ),
    ]
