# Generated by Django 3.2 on 2024-03-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtor', '0002_remove_produtor_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtor',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
