# Generated by Django 3.2 on 2024-03-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtor', '0003_alter_produtor_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtor',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
    ]
