# Generated by Django 3.2 on 2024-03-10 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('produtor', '0004_alter_produtor_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtor',
            name='dt_alteracao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='produtor',
            name='dt_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
