# Generated by Django 3.2 on 2024-03-10 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtor', '0005_auto_20240310_1003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtor',
            options={'ordering': ['nome'], 'verbose_name': 'Produtor', 'verbose_name_plural': 'Produtores'},
        ),
    ]
