# Generated by Django 3.2 on 2024-03-10 02:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fazenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Culturas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('culturas_plantadas', models.CharField(max_length=255)),
                ('fazendas', models.ManyToManyField(to='fazenda.Fazenda')),
            ],
        ),
    ]
