# Generated by Django 3.2 on 2024-03-13 21:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('ciclo_vida', models.IntegerField(default=0, help_text='Dias para completar o ciclo de vida da cultura.')),
                ('epoca_plantio', models.CharField(blank=True, help_text='Época ideal para o plantio da cultura.', max_length=255, null=True)),
                ('irrigacao_necessaria', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Cultura',
                'verbose_name_plural': 'Culturas',
                'db_table': 'brain_ag_cultura',
                'ordering': ['nome'],
            },
        ),
    ]
