# Generated by Django 3.2 on 2024-03-11 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cultura', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cultura',
            table='brain_ag_cultura',
        ),
    ]
