# Generated by Django 3.2 on 2024-03-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fazenda', '0005_remove_fazenda_cultura'),
        ('cultura', '0002_alter_cultura_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultura',
            name='fazenda',
            field=models.ManyToManyField(to='fazenda.Fazenda'),
        ),
    ]
