# Generated by Django 3.2 on 2024-03-15 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cultura', '0002_cultura_fazendas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultura',
            name='fazendas',
        ),
    ]
