# Generated by Django 3.2 on 2024-03-11 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cultura', '0003_cultura_fazenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultura',
            name='fazenda',
        ),
    ]
