# Generated by Django 3.2 on 2024-03-13 21:25

import brain_ag.fazenda.models
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cultura', '0001_initial'),
        ('produtor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fazenda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=14)),
                ('nome', models.CharField(max_length=100, validators=[brain_ag.fazenda.models.validate_nome_nao_vazio])),
                ('cidade', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=2)),
                ('area_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_agricultavel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_vegetacao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dt_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('dt_alteracao', models.DateTimeField(auto_now=True)),
                ('cultura', models.ManyToManyField(to='cultura.Cultura')),
                ('produtor', models.ManyToManyField(to='produtor.Produtor')),
            ],
            options={
                'verbose_name': 'Fazenda',
                'verbose_name_plural': 'Fazendas',
                'db_table': 'brain_ag_fazenda',
                'ordering': ['nome'],
            },
        ),
    ]
