# Generated by Django 3.2 on 2024-03-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fazenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fazenda',
            options={'ordering': ['nome'], 'verbose_name': 'Fazenda', 'verbose_name_plural': 'Fazendas'},
        ),
        migrations.AddField(
            model_name='fazenda',
            name='cnpj',
            field=models.CharField(default=123456488787, max_length=14),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='fazenda',
            table='brain_ag_fazenda',
        ),
    ]
