# Generated by Django 3.2 on 2024-03-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultura', '0003_remove_cultura_fazendas'),
        ('fazenda', '0002_remove_fazenda_cultura'),
    ]

    operations = [
        migrations.AddField(
            model_name='fazenda',
            name='cultura',
            field=models.ManyToManyField(to='cultura.Cultura'),
        ),
    ]
