# Generated by Django 3.2 on 2024-03-10 22:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fazenda', '0002_auto_20240310_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='fazenda',
            name='dt_alteracao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fazenda',
            name='dt_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
