# Generated by Django 3.2 on 2024-03-11 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fazenda', '0004_fazenda_cultura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fazenda',
            name='cultura',
        ),
    ]
