# Generated by Django 3.2 on 2024-03-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultura', '0004_remove_cultura_fazenda'),
        ('fazenda', '0005_remove_fazenda_cultura'),
    ]

    operations = [
        migrations.AddField(
            model_name='fazenda',
            name='cultura',
            field=models.ManyToManyField(to='cultura.Cultura'),
        ),
    ]
