# Generated by Django 3.2 on 2024-03-12 14:20

import brain_ag.fazenda.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fazenda', '0006_fazenda_cultura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fazenda',
            name='nome',
            field=models.CharField(max_length=100, validators=[brain_ag.fazenda.models.validate_nome_nao_vazio]),
        ),
    ]
